local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Types = require(ReplicatedStorage.Shared.Types)

local SoundService = {}

-- ===================== Private ===================== --

function SoundService:Initialize(ClientBootstrap: Types.ClientBootstrapType)
    
end

function SoundService:Setup()
    
end

-- ===================== API ===================== --

return SoundService